"""Interfaces implemented by runtime and infrastructure adapters."""

from alpha_defense.application.ports.analysis import (
    ResourceAnalysisPort,
    ResourceAnalysisRequest,
    TextAnalysisPort,
    TextAnalysisRequest,
    TextModelAnalysisPort,
)
from alpha_defense.application.ports.communications import (
    CommunicationsUnitOfWorkFactory,
    CommunicationsUnitOfWorkPort,
    ObservationRepositoryPort,
)
from alpha_defense.application.ports.content import (
    CatalogLoaderPort,
    CatalogSnapshot,
    ContentCatalogPort,
    EducationCatalogSnapshot,
    FixtureEnvelope,
    FixtureReference,
    PolicySnapshot,
    RiskThresholds,
    SignalPolicy,
    TrustedEntitiesSnapshot,
    TrustedEntity,
)
from alpha_defense.application.ports.events import (
    AuditPort,
    AuditReceipt,
    EventEnvelope,
    EventHandler,
    EventSinkPort,
    JsonValue,
    OutboxReceipt,
)
from alpha_defense.application.ports.incidents import (
    IncidentRepositoryPort,
    IncidentUnitOfWorkFactory,
    IncidentUnitOfWorkPort,
    NamespaceRiskStateRepositoryPort,
)
from alpha_defense.application.ports.protection import (
    WarningRepositoryPort,
    WarningUnitOfWorkFactory,
    WarningUnitOfWorkPort,
)
from alpha_defense.application.ports.readiness import (
    ReadinessCheck,
    ReadinessPort,
    ReadinessReport,
)
from alpha_defense.application.ports.repositories import (
    AuditRecord,
    AuditRepositoryPort,
    IdempotencyRecord,
    IdempotencyRepositoryPort,
    IdempotencyReservation,
    IdempotencyScope,
    IdempotencyState,
    OutboxMessage,
    OutboxRepositoryPort,
    OutboxState,
    RepositoryPort,
)
from alpha_defense.application.ports.runtime import Clock, IdGenerator
from alpha_defense.application.ports.threat_intel import (
    ThreatBatch,
    ThreatFeedPort,
    ThreatFeedRecord,
    ThreatFeedUnavailableError,
    ThreatRegistryRepositoryPort,
    ThreatUnitOfWorkFactory,
    ThreatUnitOfWorkPort,
)
from alpha_defense.application.ports.unit_of_work import UnitOfWorkFactory, UnitOfWorkPort

__all__ = [
    "AuditPort",
    "AuditReceipt",
    "AuditRecord",
    "AuditRepositoryPort",
    "CatalogLoaderPort",
    "CatalogSnapshot",
    "Clock",
    "CommunicationsUnitOfWorkFactory",
    "CommunicationsUnitOfWorkPort",
    "ContentCatalogPort",
    "EducationCatalogSnapshot",
    "EventEnvelope",
    "EventHandler",
    "EventSinkPort",
    "FixtureEnvelope",
    "FixtureReference",
    "IdGenerator",
    "IdempotencyRecord",
    "IdempotencyRepositoryPort",
    "IdempotencyReservation",
    "IdempotencyScope",
    "IdempotencyState",
    "IncidentRepositoryPort",
    "IncidentUnitOfWorkFactory",
    "IncidentUnitOfWorkPort",
    "JsonValue",
    "NamespaceRiskStateRepositoryPort",
    "ObservationRepositoryPort",
    "OutboxMessage",
    "OutboxReceipt",
    "OutboxRepositoryPort",
    "OutboxState",
    "PolicySnapshot",
    "ReadinessCheck",
    "ReadinessPort",
    "ReadinessReport",
    "RepositoryPort",
    "ResourceAnalysisPort",
    "ResourceAnalysisRequest",
    "RiskThresholds",
    "SignalPolicy",
    "TextAnalysisPort",
    "TextAnalysisRequest",
    "TextModelAnalysisPort",
    "ThreatBatch",
    "ThreatFeedPort",
    "ThreatFeedRecord",
    "ThreatFeedUnavailableError",
    "ThreatRegistryRepositoryPort",
    "ThreatUnitOfWorkFactory",
    "ThreatUnitOfWorkPort",
    "TrustedEntitiesSnapshot",
    "TrustedEntity",
    "UnitOfWorkFactory",
    "UnitOfWorkPort",
    "WarningRepositoryPort",
    "WarningUnitOfWorkFactory",
    "WarningUnitOfWorkPort",
]
